name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Ubuntu Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@50.17.46.99 << 'EOF'
            cd /home/ubuntu/nninebackend
            echo "Pulling latest code from origin main..."
          git pull origin main
          
          echo "Installing npm packages..."
          npm install
          
          # Ensure pm2 is installed
          if ! command -v pm2 &> /dev/null
          then
            echo "PM2 not found, installing..."
            npm install -g pm2
          fi
          
          echo "Stopping existing PM2 process if it exists..."
          pm2 stop nninebackend || true
          
          echo "Starting new PM2 process..."
          pm2 start npm --name "nninebackend" -- run dev
        EOF
#11
#update
#nvm install
#pm2 added
