name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start MongoDB Atlas
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          echo "Starting MongoDB Atlas"
          # Placeholder for starting MongoDB Atlas if needed
          # Ensure application correctly reads the MONGODB_URI from environment variables
          
      - name: Run dev server
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: npm run dev --if-present

