name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Start MongoDB Atlas
        uses: mongodb/setup-database@v1
        with:
          mongodb-uri: ${{ secrets.MONGODB_URI }}
      - name: Run dev server
        run: npm run dev --if-present
